# https://man7.org/linux/man-pages/man5/services.5.html
# https://www.gnu.org/software/libc/manual/html_node/Services-Database.html

# https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=postgres
postgresql:
  port: 5432
  protocol: tcp
  aliases:
    - postgres

consul:
  port: 8500
  protocol: tcp
